### ISSUE TITLE
Success class

### ISSUE THREAD

**Issue by zslabs** [Mevrael/bunny#18]
Hi all,
I saw there was a `errorClass` option, but am not seeing anything that would allow a "success" class to be added to input groups - is that possible?

**Comment by Mevrael** [comment]
Hi @zslabs 

Thank you for your interest in the BunnyJS and submitting your issue.

Please, in the future, always provide all the detailed information about your issue - which component exactly are you speaking about, that might be also represented in the title of the issue.

I suppose you are talking about the `src/Validation`.

Since success state to input is added in very rare cases and I can't remember any of them, there is currently no success state in Bunny Validation, thus, there is no option to add a success class.

Could you, please provide, a use-case, how exactly and when exactly you would like to add a success state to your input? I suppose during the `Validation.validateSection()` or `init()` when inputs are checked, if input passed a validation you would like to add a different class to an input group, am I right?

**Comment by zslabs** [comment]
Hey @Mevrael,
Appreciate the reply. Here's a screen shot of the various states of form inputs that I'd be looking for:

<img width="756" alt="screen shot 2017-02-05 at 2 44 37 pm" src="https://cloud.githubusercontent.com/assets/1018402/22629315/a1165b58-ebb1-11e6-8c2f-3dab1af6ac3b.png">

* Default
* Required
* Success (passed validation)
* Error (failed validation)

I use the following classes on what Bunny refers to as the the form container,

* (none for default)
* `is-required`
* `is-valid`
* `is-notValid`

**Comment by Mevrael** [comment]
0.14.9

added `ValidationConfig.classInputGroupSuccess` which defaults to BS4 `has-success`.

To activate this feature add `showvalid` attribute to `<form>`

**Comment by zslabs** [comment]
Awesome, thanks!
