### ISSUE TITLE
https://bunnyjs.com/examples/datatable/ on delete get 404

### ISSUE THREAD

**Issue by NiallJoeMaher** [Mevrael/bunny#22]
This may not be the most helpful of comments but whilst trying to delete on the datatable I get a 404 error? Is this the expected behavior for the demo?

**Comment by Mevrael** [comment]
Hi @lesniall, thank you for interest in BunnyJS.

You, obviously, can't do any actions on bunnyjs website since there are no any server. BunnyJS is a browser framework.

Yes, it is absolutely expected behavior for this demo. In your project you may do whatever you want with links or add custom listeners and do actions dynamically.
