### ISSUE TITLE
form validation capitalize

### ISSUE THREAD

**Issue by fzone** [Mevrael/bunny#4]
Hi, i trying live demo of form validation.
When i try test@test.com it gives 'This email is already in use!'
but when using Test@test.com it passed.

**Comment by Mevrael** [comment]
Hi, @fzone 

Thank you for report.

Well, in the case of ajax validation everything depends on how server processes the data and it is not Bunny Validation's problem.

In demo I use very simple plain PHP script to compare GET param with direct hardcoded string and because of that it failed since two strings wasn't equal. In real app on backend you will use any framework or ORM and usually won't have this problem.

Anyway I updated that PHP script on demo so it now ignores case.

Thanks again, let me know if you will have any other feedback, ideas or proposals.
