### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by joebordes** [Mevrael/bunny#9]
Hi,

First of all I think you have done a wonderful job. I have spent the weekend playing with the datatables and other libraries and they work very well.

I would like to know if it would be possible for you to establish a more business friendly license. Something like MIT, BSD, Apache or MPL. GPL is just to restrictive and incompatible with my open-source project. Even an LGPL would do as this is a library...

Thanks for your hard work and for sharing.

**Comment by joebordes** [comment]
Thank you!!

I have updated the library and started playing with the new code. Looks like you have been busy :-)
I have included it in coreBOS: https://github.com/tsolucio/corebos using the datatable to page in the reports.

I look forward to using some of the other components also.

**Comment by Mevrael** [comment]
Thanks for your kind words!

Yeah, you are right. Didn't had time to answer since I prefer to code first and even for that today, unfortunately, I don't have so much time I would like to :)

Nice project you have! I remember was building something similar on PHP long time ago. DataTables are very important for such kind of business apps and I had a project with a lot of custom and huge jQuery DataTables and it was a pain to maintain it. This is definitely what I will not allow to happen with BunnyJS.

If you will have any feedback, ideas, proposals on any component even if it doesn't exists, please let me know.

DataTable is still missing some important features like column filtering. Hope it will be available until 1.0.
